data = {'lr'       : 1e-4,
'dream_length'     : 11025 * 2,
'num_unrollings'   : 100,
'seg_len'          : 1024,
'label_shape'      : (100,1),
'output_shape'     : (100,1),
'int_cursor_inc'   : 1024,
'ext_cursor_inc'   : 1,
'weight_stddev'    : 1e-3,
'cursor_inc'       : 1,
'num_epochs'       : 8,
'print_freq'       : 500,
'plot_freq'        : 1000,
'audio_freq'       : 2000,
'noise_scale'      : 0.05,
'sampling_rate'    : 11025,
'use_plotting'     : False,
'save_audio'       : True,
'use_seq_dreams'   : False,
'use_dropout'      : True,
'input_keep_prob'  : 0.9,
'output_keep_prob' : 1.0,
'seed_advance'     : ['random'],
'device'           : 'cpu:0',
'base_name'        : 'samplewise_guitar',
'input_names'      : ['training'],
'input_fn_list'    : ['model_inputs/limited_guitar.wav']}
